export const jobRoles = [
  { title: "Backend", category: "Engineering" },
  { title: "Frontend", category: "Engineering" },
  { title: "Fullstack", category: "Engineering" },
  { title: "IOS", category: "Engineering" },
  { title: "Flutter", category: "Engineering" },
  { title: "React Native", category: "Engineering" },
  { title: "Android", category: "Engineering" },
  { title: "Tech Lead", category: "Engineering" },
  { title: "Dev-Ops", category: "Engineering" },
  { title: "Data Engineer", category: "Engineering" },
  { title: "Data Science", category: "Engineering" },
  { title: "Computer Vision", category: "Engineering" },
  { title: "Nlp", category: "Engineering" },
  { title: "Deep Learning", category: "Engineering" },
  { title: "Test / QA", category: "Engineering" },
  { title: "Web3", category: "Engineering" },
  { title: "Data Infrastructure", category: "Engineering" },
  { title: "Designer", category: "DESIGN" },
  { title: "Design Manager", category: "DESIGN" },
  { title: "Graphic Designer", category: "DESIGN" },
  // Add more options as needed
];
